# Replication Controller for springapp
apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-controller
spec:
  replicas: 2
  selector:
    app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: venkatesh9691/prod
        name: tomcat
        ports:
        - containerPort: 8080  
---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tomcat
